backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('pool_app.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

backend/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from .views import register_view, signin_view, logout_view, user_detail

app_name = 'users'

urlpatterns = [
    path('signin/', signin_view, name='login'),
    path('signup/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('me/', user_detail, name='user_detail'),
]

backend/users/models.py
from datetime import date

from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.db import models


class User(AbstractUser):
    '''
    Переопределенная модель пользователя.
    '''

    date_of_birth = models.DateField(blank=True, null=True)

    phone_regex = RegexValidator(regex=r'^(?:\+7|8)\d{10}$',
                                 message="Неверный формат номера телефона")
    phone_number = models.CharField(validators=[phone_regex], max_length=12,
                                    unique=True, blank=False, null=False)

    @property
    def active_pool_pass(self):
        return self.pool_pass.filter(is_active=True).first()

    @property
    def age(self):
        if self.date_of_birth is not None:
            today = date.today()
            return today.year - self.date_of_birth.year - (
                    (today.month, today.day) < (self.date_of_birth.month,
                                                self.date_of_birth.day)
            )

        return None

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = 'username',

    def __str__(self):
        return self.username

backend/pool_app/forms.py
from django import forms

from .models import InstructorReview, PoolReview, PoolPass, Lesson


class InstructorReviewForm(forms.ModelForm):
    class Meta:
        model = InstructorReview
        fields = ['rating', 'comment']


class PoolReviewForm(forms.ModelForm):
    class Meta:
        model = PoolReview
        fields = ['rating', 'comment']


class PoolPassForm(forms.ModelForm):
    class Meta:
        model = PoolPass
        fields = ['pass_type']


class LessonSignUpForm(forms.ModelForm):
    class Meta:
        model = Lesson
        fields = []


class JobApplicationForm(forms.Form):
    name = forms.CharField(label="Ваше имя", max_length=100)
    email = forms.EmailField(label="Ваш Email")
    message = forms.CharField(label="Сообщение", widget=forms.Textarea)

backend/users/forms.py
from django import forms
from django.core.validators import RegexValidator

from .models import User


class UserCustomForm(forms.ModelForm):
    '''
    форма для создания и обновления пользователя
    '''
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Подтверждение пароля',
                                widget=forms.PasswordInput)

    phone_regex = RegexValidator(regex=r'^(?:\+7|8)\d{10}$',
                                 message="Неверный формат номера телефона")
    phone_number = forms.CharField(
        label='Номер телефона',
        validators=[phone_regex],
        max_length=12,
        required=True
    )

    date_of_birth = forms.DateField(label='Дата рождения',
        widget=forms.DateInput(attrs={'type': 'date'})
    )

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email',
                  'date_of_birth', 'phone_number']

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Пароли не совпадают")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

backend/users/views.py
from datetime import date
from django.apps import apps
from django.contrib.auth import login, logout, get_user_model
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from pool_app.models import PoolPass
from .forms import UserCustomForm


User = get_user_model()


def register_view(request):
    if request.method == 'POST':
        form = UserCustomForm(request.POST)
        if form.is_valid():
            form.save()

            return redirect('users:login')
    else:
        form = UserCustomForm()
    return render(
        request, 'users/registration.html', {'form': form}
    )


def signin_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect('pool_app:index')
    else:
        form = AuthenticationForm()
    return render(request, 'users/login.html', {'form': form})


def logout_view(request):
    logout(request)
    return redirect('users:login')


@login_required
def user_detail(request):
    user = request.user
    pool_pass = user.active_pool_pass
    signed_up_lessons = user.lessons.all()
    age = None

    if user.active_pool_pass:
        user.active_pool_pass.check_activation()

    if user.date_of_birth:
        today = date.today()
        age = (
                today.year - user.date_of_birth.year -
                ((today.month, today.day) < (user.date_of_birth.month,
                                             user.date_of_birth.day))
        )

    if user.date_of_birth:
        today = date.today()
        age = (
            today.year - user.date_of_birth.year -
            ((today.month, today.day) < (user.date_of_birth.month,
                                         user.date_of_birth.day))
        )

    if request.method == 'POST':
        form = UserCustomForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('users:user_detail')
    else:
        form = UserCustomForm(instance=user)

    context = {
        'form': form,
        'age': age,
        'pool_pass': pool_pass,
        'signed_up_lessons': signed_up_lessons
    }

    if user.is_staff:
        users = User.objects.all()
        context['users'] = users

    return render(request, 'users/user_detail.html', context)

backend/users/templates/users/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2 class="text-center">Вход в систему</h2>
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username" class="form-label">Имя пользователя</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <div class="mb-3">
                    <label for="password" class="form-label">Пароль</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-primary">Войти</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

backend/users/templates/users/registration.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h2 class="mb-4">Форма регистрации</h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group mb-3">
                        <label for="id_username">Имя пользователя</label>
                        <input type="text" name="username" class="form-control" id="id_username" required>
                    </div>
                    <div class="form-group mb-3">
                        <label for="id_first_name">Имя</label>
                        <input type="text" name="first_name" class="form-control" id="id_first_name" required>
                    </div>
                    <div class="form-group mb-3">
                        <label for="id_last_name">Фамилия</label>
                        <input type="text" name="last_name" class="form-control" id="id_last_name" required>
                    </div>
                    <div class="form-group mb-3">
                        <label for="id_email">Электронная почта</label>
                        <input type="email" name="email" class="form-control" id="id_email" required>
                    </div>
                    <div class="form-group mb-3">
                        <label for="id_date_of_birth">Дата рождения</label>
                        <input type="date" name="date_of_birth" class="form-control" id="id_date_of_birth" required>
                    </div>
                    <div class="form-group mb-3">
                        <label for="id_phone_number">Номер телефона</label>
                        <input type="text" name="phone_number" class="form-control" id="id_phone_number" required>
                    </div>
                    <div class="form-group mb-3">
                        <label for="id_password1">Пароль</label>
                        <input type="password" name="password1" class="form-control" id="id_password1" required>
                    </div>
                    <div class="form-group mb-3">
                        <label for="id_password2">Подтверждение пароля</label>
                        <input type="password" name="password2" class="form-control" id="id_password2" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

backend/users/templates/users/user_detail.html
{% extends 'base.html' %}

{% block content %}

{% if users %}
<div class="container mt-5 mb-5">
    <h2 class="mb-4">Список пользователей</h2>
    <div class="table-responsive">
        <table class="table table-bordered table-hover">
            <thead class="table-primary">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Логин</th>
                    <th scope="col">Имя</th>
                    <th scope="col">Фамилия</th>
                    <th scope="col">Email</th>
                    <th scope="col">Дата рождения</th>
                    <th scope="col">Номер телефона</th>
                    <th scope="col">Возраст</th>
                    <th scope="col">Абонемент</th>
                </tr>
            </thead>
            <tbody>
                {% for user in users %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>{{ user.username }}</td>
                    <td>{{ user.first_name }}</td>
                    <td>{{ user.last_name }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.date_of_birth|date:"d.m.Y" }}</td>
                    <td>{{ user.phone_number }}</td>
                    <td>{{ user.age }}</td>
                    {% if user.active_pool_pass %}
                    <td>{{ user.active_pool_pass }}</td>
                    {% else %}
                    <td> - </td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% else %}
<div class="container mt-5">
    <h2 class="mb-4">Детали профиля</h2>
    {% if pool_pass %}
    <h3>Активный абонемент</h3>
    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th scope="col">№</th>
                    <th scope="col">Тип</th>
                    <th scope="col">Куплен</th>
                    <th scope="col">Заканчивается</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">{{ pool_pass.pk }}</th>
                    <td>{{ pool_pass.get_pass_type_display }}</td>
                    <td>{{ pool_pass.start_date }}</td>
                    <td>{{ pool_pass.end_date }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    {% endif %}
    <form method="post">
                {% csrf_token %}
                <div class="form-group mb-3">
                    <label for="id_username">{{ form.username.label }}</label>
                    <input type="text" name="username" class="form-control"
                           id="id_username" required
                           value="{{ form.username.value|default_if_none:'' }}">
                </div>
                <div class="form-group mb-3">
                    <label for="id_first_name">{{ form.first_name.label }}</label>
                    <input type="text" name="first_name" class="form-control"
                           id="id_first_name" required
                           value="{{ form.first_name.value|default_if_none:'' }}">
                </div>
                <div class="form-group mb-3">
                    <label for="id_last_name">{{ form.last_name.label }}</label>
                    <input type="text" name="last_name" class="form-control"
                           id="id_last_name" required
                           value="{{ form.last_name.value|default_if_none:'' }}">
                </div>
                <div class="form-group mb-3">
                    <label for="id_email">{{ form.email.label }}</label>
                    <input type="email" name="email" class="form-control"
                           id="id_email" required
                           value="{{ form.email.value|default_if_none:'' }}">
                </div>
                <div class="form-group mb-3">
                    <label>Дата рождения</label>
                    <input type="text" class="form-control"
                           value="{{ user.date_of_birth }}" readonly>
                </div>
                <div class="form-group mb-3">
                    <label for="id_phone_number">{{ form.phone_number.label }}</label>
                    <input type="text" name="phone_number" class="form-control"
                           id="id_phone_number" required
                           value="{{ form.phone_number.value|default_if_none:'' }}">
                </div>
                <div class="form-group mb-3">
                    <label>Возраст</label>
                    <input type="text" class="form-control" value="{{ age }}"
                           readonly>
                </div>
                <button type="submit" class="btn btn-primary">Сохранить
                    изменения
                </button>
            </form>
</div>
<div class="container mt-3 mb-5">
    <h3>Занятия, на которые вы записаны:</h3>
    {% if signed_up_lessons %}
    <ul class="list-group">
        {% for lesson in signed_up_lessons %}
        <li class="list-group-item">
            <strong>{{ lesson.title }}</strong> (Инструктор: {{ lesson.instructor.user.username }}) <br>
            Время начала: {{ lesson.start_time }} <br>
            Время окончания: {{ lesson.end_time }} <br>
            Описание: {{ lesson.description }} <br>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>Вы пока не записаны ни на одно занятие.</p>
    {% endif %}
</div>
{% endif %}

{% endblock %}