backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('pool_app.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

backend/pool_app/urls.py
from django.urls import path

from .views import (instructor_list, lesson_list, instructor_detail,
                    lesson_detail, add_instructor_review, post_list,
                    index, add_pool_review, review_list, apply_for_job,
                    instructor_review_list, buy_pool_pass, sign_up_for_lesson,
                    job_list, job_success)

app_name = 'pool_app'

urlpatterns = [
    path('', index, name='index'),
    path('instructors/', instructor_list, name='instructor_list'),
    path('lessons/<int:lesson_id>/signup/', sign_up_for_lesson,
         name='sign_up_for_lesson'),

    path('lessons/', lesson_list, name='lesson_list'),
    path('instructors/<int:pk>/', instructor_detail, name='instructor_detail'),
    path('lessons/<int:pk>/', lesson_detail, name='lesson_detail'),
    path('instructors/<int:instructor_id>/add_review/', add_instructor_review,
         name='add_instructor_review'),
    path('add_pool_review/', add_pool_review, name='add_pool_review'),
    path('review/', review_list, name='review_list'),
    path('instructor-review/', instructor_review_list,
         name='instructor_review_list'),
    path('buy_pass', buy_pool_pass, name='buy_pool_pass'),
    path('posts/', post_list, name='post_list'),
    path('jobs/apply/', apply_for_job, name='apply_for_job'),
    path('jobs/success/', job_success, name='job_success'),
    path('jobs/', job_list, name='job_list'),
]

backend/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from .views import register_view, signin_view, logout_view, user_detail

app_name = 'users'

urlpatterns = [
    path('signin/', signin_view, name='login'),
    path('signup/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
    path('me/', user_detail, name='user_detail'),
]

backend/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
<body>
<nav class="navbar navbar-expand-lg  " style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'pool_app:index' %}">Главная</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pool_app:instructor_list' %}">Инструкторы</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pool_app:lesson_list' %}">Занятия</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Отзывы
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'pool_app:review_list' %}">О нас</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'pool_app:instructor_review_list' %}">О инструкторах</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pool_app:post_list' %}">Новости</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pool_app:job_list' %}">Вакансии</a>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto">
        {% if user.is_authenticated %}
        {% if not user.active_pool_pass %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'pool_app:buy_pool_pass' %}">Купить абонемент</a>
            </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:user_detail' %}">Мой профиль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register' %}">Регистрация</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

{% block content %}
{% endblock %}
<footer class="bg-body-tertiary text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2024 Copyright:
    <a class="text-body" href="https://github.com/chelnik">chelnik</a>
  </div>
  <!-- Copyright -->
</footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>